apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-manual-pv
spec:
  capacity:
    storage: 10Gi # The size of the volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain # What happens when the PVC is deleted
  storageClassName: ebs-gp3 # Optional: can assign a class
  nfs:
    path: /tmp
    server: 172.17.0.2