apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Requesting 5GB of space
  storageClassName: fast-ssd # Requesting storage from the "fast-ssd" class
  # selector: # (Optional) Can add labels to select a specific PV
  #   matchLabels:
  #     type: fast-ssd